
#include "spike_generator_qkv8.h"
#include "predefs_CSpikeGeneratorqkv8Model.h" // Port and Var definitions, is autogenerated


int spk_guard(runState *rs){
    return 1;
}

void run_spk(runState *rs){
    
    // Generate random spike data
    uint32_t spike_data[s_out_q_0.size * 8];
    
    for (uint32_t i = 0; i < s_out_q_0.size * 8; ++i)
    {
        uint32_t r = (uint32_t)(rand() % 100);
        if (r < spike_prob[0])
        {
            spike_data[i] = 1;
        }
        else
        {
            spike_data[i] = 0;
        }
    }
    
    // Send spikes
    uint32_t cur_pos = 0;
    send_vec_dense(rs, &s_out_q_0, spike_data);
    send_vec_dense(rs, &s_out_k_0, spike_data);
    send_vec_dense(rs, &s_out_v_0, spike_data);
    cur_pos += s_out_q_0.size;
    send_vec_dense(rs, &s_out_q_1, spike_data + cur_pos);
    send_vec_dense(rs, &s_out_k_1, spike_data + cur_pos);
    send_vec_dense(rs, &s_out_v_1, spike_data + cur_pos);
    cur_pos += s_out_q_1.size;
    send_vec_dense(rs, &s_out_q_2, spike_data + cur_pos);
    send_vec_dense(rs, &s_out_k_2, spike_data + cur_pos);
    send_vec_dense(rs, &s_out_v_2, spike_data + cur_pos);
    cur_pos += s_out_q_2.size;
    send_vec_dense(rs, &s_out_q_3, spike_data + cur_pos);
    send_vec_dense(rs, &s_out_k_3, spike_data + cur_pos);
    send_vec_dense(rs, &s_out_v_3, spike_data + cur_pos);
    cur_pos += s_out_q_3.size;
    send_vec_dense(rs, &s_out_q_4, spike_data + cur_pos);
    send_vec_dense(rs, &s_out_k_4, spike_data + cur_pos);
    send_vec_dense(rs, &s_out_v_4, spike_data + cur_pos);
    cur_pos += s_out_q_4.size;
    send_vec_dense(rs, &s_out_q_5, spike_data + cur_pos);
    send_vec_dense(rs, &s_out_k_5, spike_data + cur_pos);
    send_vec_dense(rs, &s_out_v_5, spike_data + cur_pos);
    cur_pos += s_out_q_5.size;
    send_vec_dense(rs, &s_out_q_6, spike_data + cur_pos);
    send_vec_dense(rs, &s_out_k_6, spike_data + cur_pos);
    send_vec_dense(rs, &s_out_v_6, spike_data + cur_pos);
    cur_pos += s_out_q_6.size;
    send_vec_dense(rs, &s_out_q_7, spike_data + cur_pos);
    send_vec_dense(rs, &s_out_k_7, spike_data + cur_pos);
    send_vec_dense(rs, &s_out_v_7, spike_data + cur_pos);
    

}
