
#include "spiking_self_attention_8.h"
#include "predefs_CSpikingSelfAttention8Model.h" // Port and Var definitions, is autogenerated

int spk_guard(runState *rs){
    return 1;
}

void run_spk(runState *rs){
    uint32_t spikes_data_q[spikes_in_q_0.size * 8]; // [spikes_in_q_0.size][8]
    uint32_t spikes_data_k[spikes_in_k_0.size * 8];
    uint32_t spikes_data_v[spikes_in_v_0.size * 8];

    uint32_t attn_map[num_heads[0]][8][8];
    uint32_t stride = spikes_in_q_0.size;
    uint32_t channel_dim = spikes_in_q_0.size / num_heads[0];

    uint32_t spikes_data_out[spikes_out_0.size * 8];

    uint32_t cur_pos = 0;
    recv_vec_dense(rs, &spikes_in_q_0, spikes_data_q + cur_pos);
    recv_vec_dense(rs, &spikes_in_k_0, spikes_data_k + cur_pos);
    recv_vec_dense(rs, &spikes_in_v_0, spikes_data_v + cur_pos);
    cur_pos += spikes_in_q_0.size;
    recv_vec_dense(rs, &spikes_in_q_1, spikes_data_q + cur_pos);
    recv_vec_dense(rs, &spikes_in_k_1, spikes_data_k + cur_pos);
    recv_vec_dense(rs, &spikes_in_v_1, spikes_data_v + cur_pos);
    cur_pos += spikes_in_q_1.size;
    recv_vec_dense(rs, &spikes_in_q_2, spikes_data_q + cur_pos);
    recv_vec_dense(rs, &spikes_in_k_2, spikes_data_k + cur_pos);
    recv_vec_dense(rs, &spikes_in_v_2, spikes_data_v + cur_pos);
    cur_pos += spikes_in_q_2.size;
    recv_vec_dense(rs, &spikes_in_q_3, spikes_data_q + cur_pos);
    recv_vec_dense(rs, &spikes_in_k_3, spikes_data_k + cur_pos);
    recv_vec_dense(rs, &spikes_in_v_3, spikes_data_v + cur_pos);
    cur_pos += spikes_in_q_3.size;
    recv_vec_dense(rs, &spikes_in_q_4, spikes_data_q + cur_pos);
    recv_vec_dense(rs, &spikes_in_k_4, spikes_data_k + cur_pos);
    recv_vec_dense(rs, &spikes_in_v_4, spikes_data_v + cur_pos);
    cur_pos += spikes_in_q_4.size;
    recv_vec_dense(rs, &spikes_in_q_5, spikes_data_q + cur_pos);
    recv_vec_dense(rs, &spikes_in_k_5, spikes_data_k + cur_pos);
    recv_vec_dense(rs, &spikes_in_v_5, spikes_data_v + cur_pos);
    cur_pos += spikes_in_q_5.size;
    recv_vec_dense(rs, &spikes_in_q_6, spikes_data_q + cur_pos);
    recv_vec_dense(rs, &spikes_in_k_6, spikes_data_k + cur_pos);
    recv_vec_dense(rs, &spikes_in_v_6, spikes_data_v + cur_pos);
    cur_pos += spikes_in_q_6.size;
    recv_vec_dense(rs, &spikes_in_q_7, spikes_data_q + cur_pos);
    recv_vec_dense(rs, &spikes_in_k_7, spikes_data_k + cur_pos);
    recv_vec_dense(rs, &spikes_in_v_7, spikes_data_v + cur_pos);

    // multiply q and k transpose to get attention map

    for (uint32_t i = 0; i < num_heads[0]; ++i)
    {
        for (uint32_t j = 0; j < 8; ++j)
        {
            for (uint32_t k = 0; k < 8; ++k)
            {
                uint32_t sum = 0;
                for (uint32_t l = 0; l < channel_dim; ++l)
                {
                    sum += spikes_data_q[i * channel_dim + j * stride + l] * spikes_data_k[i * channel_dim + k * stride + l];
                }
                attn_map[i][j][k] = sum;
            }

        }
    }

    // attn map multiply by v to get output
    for (uint32_t i = 0; i < num_heads[0]; ++i)
    {
        for (uint32_t l = 0; l < channel_dim; ++l)
        {
            for (uint32_t j = 0; j < 8; ++j)
            {
                uint32_t sum = 0;
                for (uint32_t k = 0; k < 8; ++k)
                {
                    sum += attn_map[i][j][k] * spikes_data_v[i * channel_dim + k * stride + l];
                }
                spikes_data_out[i * channel_dim + j * stride + l] = sum;
            }
        }
    }

    cur_pos = 0;
    send_vec_dense(rs, &spikes_out_0, spikes_data_out + cur_pos);
    cur_pos += spikes_out_0.size;
    send_vec_dense(rs, &spikes_out_1, spikes_data_out + cur_pos);
    cur_pos += spikes_out_1.size;
    send_vec_dense(rs, &spikes_out_2, spikes_data_out + cur_pos);
    cur_pos += spikes_out_2.size;
    send_vec_dense(rs, &spikes_out_3, spikes_data_out + cur_pos);
    cur_pos += spikes_out_3.size;
    send_vec_dense(rs, &spikes_out_4, spikes_data_out + cur_pos);
    cur_pos += spikes_out_4.size;
    send_vec_dense(rs, &spikes_out_5, spikes_data_out + cur_pos);
    cur_pos += spikes_out_5.size;
    send_vec_dense(rs, &spikes_out_6, spikes_data_out + cur_pos);
    cur_pos += spikes_out_6.size;
    send_vec_dense(rs, &spikes_out_7, spikes_data_out + cur_pos);
}